#!/usr/bin/env python3
"""Create the analysis workspace for business-flow-documenter.

Usage:
  python create_workspace.py [repo_root]
"""
from __future__ import annotations

import sys
from pathlib import Path

FILES = {
    '.ai-analysis/repo-map.md': '# Repo Map\n\n## Technology stack\n\n## Runtime and entrypoints\n\n## Core directories\n\n## Major configuration files\n\n## System layering\n\n## Core modules\n\n## Modules needing deeper analysis\n\n## Evidence\n\n## Uncertainties\n',
    '.ai-analysis/domain-model.md': '# Business Domain Model\n\n## Domain overview\n\n## Glossary\n\n| Term | Meaning | Evidence |\n|---|---|---|\n\n## Core entities\n\n| Entity | Meaning | Evidence |\n|---|---|---|\n\n## Roles\n\n| Role | Meaning | Evidence |\n|---|---|---|\n\n## Status enums\n\n| Status | Meaning | Source |\n|---|---|---|\n\n## Entity relationships\n\n## Uncertainties\n',
    '.ai-analysis/api-analysis.md': '# API / Entry Analysis\n\n## Entrypoint overview\n\n| Method / Type | Path / Entry | Business action | Handler | Evidence |\n|---|---|---|---|---|\n\n## Call chains\n\n## Request input summary\n\n## Response output summary\n\n## Middleware / authorization\n\n## Uncertainties\n',
    '.ai-analysis/service-flows.md': '# Service Flow Analysis\n\n## Core business flows\n\n| Flow | Trigger | Core service | Notes |\n|---|---|---|---|\n\n## Flow details\n\n## Uncertainties\n',
    '.ai-analysis/data-model.md': '# Data Model Analysis\n\n## Core tables / models\n\n| Table / Model | Business meaning | Evidence |\n|---|---|---|\n\n## Field notes\n\n## Relationships\n\n| Entity A | Relationship | Entity B | Evidence |\n|---|---|---|---|\n\n## Read/write scenarios\n\n## Data lifecycle\n\n## Uncertainties\n',
    '.ai-analysis/frontend-flow.md': '# Frontend / UI Flow Analysis\n\n## Pages / routes\n\n| Page | Route | Business meaning | Evidence |\n|---|---|---|---|\n\n## User operation paths\n\n## Frontend API calls\n\n## State management\n\n## Frontend-backend mapping\n\n## Uncertainties\n',
    '.ai-analysis/integrations.md': '# Integration Analysis\n\n## External dependencies\n\n| System | Purpose | Call location | Evidence |\n|---|---|---|---|\n\n## Integration method\n\n## Call timing\n\n## Inputs and outputs\n\n## Retry / fallback logic\n\n## System boundaries\n\n## Uncertainties\n',
    '.ai-analysis/tasks-and-messaging.md': '# Tasks and Messaging Analysis\n\n## Scheduled jobs\n\n| Job | Trigger | Business role | Evidence |\n|---|---|---|---|\n\n## Async jobs\n\n| Job | Enqueue location | Consumer | Business role | Evidence |\n|---|---|---|---|---|\n\n## Message flows\n\n| Message / Event | Producer | Consumer | Business meaning |\n|---|---|---|---|\n\n## Retry behavior\n\n## Impact on main flows\n\n## Uncertainties\n',
    '.ai-analysis/permissions-and-validation.md': '# Permissions and Validation Analysis\n\n## Authentication\n\n## Authorization model\n\n| Permission / Role | Allowed actions | Evidence |\n|---|---|---|\n\n## Input validation\n\n| Entry | Rule | Evidence |\n|---|---|---|\n\n## Business rule validation\n\n## Sensitive operations\n\n## Audit logs\n\n## Uncertainties\n',
    '.ai-analysis/tests-verification.md': '# Tests Verification\n\n## Business flows covered by tests\n\n| Test file | Business behavior | Evidence |\n|---|---|---|\n\n## Business rules from tests\n\n## Error and boundary cases\n\n## Mapping to flow analysis\n\n## Gaps found\n\n## Uncertainties\n',
    '.ai-analysis/verification.md': '# Verification Report\n\n## Verified conclusions\n\n## Claims with insufficient evidence\n\n## Conflicts\n\n## Potentially missing flows\n\n## Questions for human confirmation\n\n| Question | Reason | Suggested owner |\n|---|---|---|\n',
    'docs/business-flow.md': '# Business Flow Documentation\n\nDraft generated by business-flow-documenter. Replace this file with the final verified document.\n',
}


def main() -> int:
    root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd().resolve()
    created = []
    for relative_path, content in FILES.items():
        target = root / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists():
            target.write_text(content, encoding='utf-8')
            created.append(relative_path)
    print(f'Workspace ready at {root}')
    print(f'Created {len(created)} files')
    for item in created:
        print(f'- {item}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
